---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.kafka.port }}
  selector:
    app: kafka
