---
apiVersion: v1
kind: Service
metadata:
  name: kafka-manager
  namespace: kafka
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: {{ .Values.manager.externalPort }}
    targetPort: {{ .Values.manager.containerPort }}
  selector:
    app: kafka-manager
  type: LoadBalancer