---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-manager
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.manager.replicas }}
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: sheepkiller/kafka-manager:latest
        env:
        - name: ZK_HOSTS
          value: "zookeeper.kafka.svc.cluster.local:2181"
        ports:
        - containerPort: {{ .Values.manager.containerPort }}
