# the headless service is for PetSet DNS, this one is for clients
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper
  type: LoadBalancer
