kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ template "webui-fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Values.WebUi.Component}}"
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{.Values.WebUi.Component}}
  template:
    metadata:
      labels:
        component: {{.Values.WebUi.Component}}
    spec:
      containers:
        - name: {{.Values.WebUi.Component}}
          image: "{{.Values.WebUi.Image}}"
          ports:
            - containerPort: {{.Values.WebUi.ProxyPort}}
          resources:
            requests:
              cpu: 100m
          args:
            - "spark-master:{{.Values.WebUi.ServicePort}}"