apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.Master.Component}}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  replicas: {{default 1 .Values.Master.Replicas}}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: {{.Values.Master.Component}}
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: {{.Values.Master.Component}}
    spec:
      containers:
        - name: {{.Values.Master.Component}}
          imagePullPolicy: "{{.Values.Master.ImagePullPolicy}}"
          image: "{{.Values.Master.Image}}:{{.Values.Master.ImageTag}}"
          ports:
            - containerPort: {{.Values.Master.ContainerPort}}
            - containerPort: {{.Values.WebUi.ContainerPort}}
          resources:
            requests:
              cpu: "{{.Values.Master.Resources.Requests.Cpu}}"
              memory: "{{.Values.Master.Resources.Requests.Memory}}"
            limits:
              cpu: "{{.Values.Master.Resources.Limits.Cpu}}"
              memory: "{{.Values.Master.Resources.Limits.Memory}}"
          env:
          - name: SPARK_DAEMON_MEMORY
            value: {{ default "1g" .Values.Master.DaemonMemory | quote }}